name: autodeploy
run-name: ${{ github.actor }} is deploying to the server
on: [push]
jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: 'random'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz ./dist/ root@${{ secrets.SSH_HOST }}:/var/wwww/fabdev.software/public_html
